### ISSUE TITLE
Bug: Timer restarts i Discord everytime a note is opened for edit.

### ISSUE THREAD

**Issue by henrikfalk** [lukeleppan/obsidian-discordrpc#1]
Plugin version 1.3.2
Obsidian v0.10.10

Bug:  The timer restarts on Discord every time I open a note to edit
Even though I have the following settings:

![Screenshot_20210125_174045](https://user-images.githubusercontent.com/30142914/105736121-bf753600-5f34-11eb-89c2-7af7f0a357e3.png)

Another user on Discord have the same issue.

**Comment by lukeleppan** [comment]
Thank you for the issue. I will look into the bug as soon as possible.

**Comment by lukeleppan** [comment]
Okay I see the bug. It's a sneaky one, probably just one line giving troubles.

**Comment by lukeleppan** [comment]
I think I fixed it. I'll close the issue now. Please let me no if something is still broken. Thank you.
